config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts do
    resources :comments, only:[:create,:edit, :update,:destroy]
    resources :likes, only:[:create,:destroy]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :logged_in_user
	before_action :load_comment, only: [:edit, :update,:destroy]
	before_action :load_post
	def create
		@comment =Comment.new comment_params

		 if @comment.save
		 	respond_to do |format|
		 		format.html
		 		format.js
		 		format.json
		 	end
		 else
		 	respond_to do |format|
		 		format.html
		 		format.js
		 		format.json
		 	end
		 end
	end

	def edit

	end

	def update
		if @comment.update_attributes comment_params
			respond_to do |format|
		 		format.html
		 		format.js
		 		format.json
		 	end
		else
			respond_to do |format|
		 		format.html
		 		format.js
		 		format.json
		 	end
		end
	end

	def delete

	end

	def destroy
		if @comment.destroy
			respond_to do |format|
		 		format.html
		 		format.js
		 		format.json
		 	end
		else
			respond_to do |format|
		 		format.html
		 		format.js
		 		format.json
		 	end
		end
	end


	private

	def comment_params
		params.require(:comment).permit :user_id,:post_id,:content
	end

	def load_comment
		@comment= current_user.comments.find_by id: params[:id]

		return if @comment

		flash[:danger] = "Access denied"
		redirect_to root_path 
	end

	def load_post
		@post = Post.find_by id: params[:post_id]
		redirect_to root_path unless @post	
	end

	def correct_user
		
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="media" id="comment-<%= comment.id %>">
	  <%= gravatar_for(comment.user) %>
	  <div class="media-body  comment-content " >
	    <h5 class="mt-0"> 
	    <%= comment.user.name %> 
	    	<small>
	    		<%=  time_ago_in_words(comment.created_at) %> ago 
	    	</small>
	    </h5>
	    <%= comment.content %>
	    <%= link_to "Edit" ,edit_post_comment_path(comment, post_id: @post.id) ,remote: true %>
	    <%= link_to "Delete" ,[@post, comment],method: :delete ,remote: true,data: {confirm:"Are you sure?"}  %>
	  </div>
	  <div class="edit-form">
	  </div>
</div>

app/views/comments/_form.html.erb
 <%= form_for [@post, @comment], remote:true  do |f| %>
	        <%= f.hidden_field :user_id,value: current_user.id %>
	        <%= f.hidden_field :post_id, value: @post.id %>
		    <div class="input-group mb-3">
		      <%= f.text_field :content, 
		      class: "form-control",
		      	placeholder: "Enter your commnet",
		      	area: {
		      		label:"Enter your content",
		      		describedby: "basic-addon2"
		      	}
		      %>
			  
			  <div class="input-group-append">
			    <button class="btn btn-outline-secondary" type="submit">Comment</button>
			  </div>


			</div>
<% end %>

app/views/comments/create.js.erb
$('.list-comments').prepend('<%= j render(partial: "comments/comment", locals: {comment: @comment}) %>')
$('input#comment_content').val('')

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').remove();

app/views/comments/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@comment) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>

	  <%= f.label :content %>
	  <%= f.text_field :content, class: 'form-control' %>

	  <%= f.submit "save", class: "btn btn-primary" %>
	<% end %>

    
  </div>
</div>

app/views/comments/edit.js.erb
$('#comment-<%= @comment.id %>').find('.comment-content').first().hide();
$('#comment-<%= @comment.id %>').find('.edit-form').html('<%= j render "comments/form" %>');

app/views/comments/update.js.erb
$('#comment-<%= @comment.id %>').html('<%= j render @comment %>')